name: phoenix_wings
description: Phoenix Channel client for Dart
version: 1.0.3
homepage: https://github.com/mfeckie/phoenix_wings

dev_dependencies:
  test: ^1.20.2
  mockito: ^5.1.0
  stream_channel: ^2.1.0
  intl: ^0.17.0
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  
environment:
  sdk: ">=2.15.1 <3.0.0"
